import { analyze, melodyFromVocal, refineHarmony } from '../src/cover/analyze';
import { separateVocal } from '../src/cover/vocal';
import { genSong } from './lib/songgen';
import { SONGS } from './cover-bench';
const o = SONGS.find((x) => x.label.startsWith(process.argv[2]))!, g = genSong(o), t = g.truth;
const a = analyze([g.L, g.R], g.sr);
const sep = separateVocal([g.L, g.R], g.sr);
refineHarmony(sep.inst, a);
const mv = melodyFromVocal(sep.vocal, a)!;
const k = Math.round((a.offset - t.offset) / ((4 * 60) / t.bpm));
console.log('truth', t.melody.filter((n) => n.t - k * 4 < 16).map((n) => `${(n.t - k * 4).toFixed(2)}:${n.midi % 12}/${n.len.toFixed(2)}`).join(' '));
console.log('got  ', mv.filter((n) => n.t < 16).map((n) => `${n.t.toFixed(2)}:${(n.midi - a.shift + 120) % 12}/${n.len.toFixed(2)}`).join(' '));
